### ISSUE TITLE
Vote on Project

### ISSUE THREAD

**Issue by Philip-Clark** [Club-40/group-project-1#10]
Vote for a project to do from the list of submitted projects

**Comment by crespire** [comment]
The link in case folks start here: https://github.com/orgs/Club-40/discussions/5

**Comment by Philip-Clark** [comment]
> The link in case folks start here: https://github.com/orgs/Club-40/discussions/5

Good catch. Thanks

**Comment by Philip-Clark** [comment]
Voting Closed. Pantry app won
